#Accelerometr & Gyroscope GPIO
pinOut.accelerometr: 2
pinOut.gyroscope: 3

#ESC controllers GPIO
pinOut.esc.forwardLeft: 14
pinOut.esc.forwardRight: 15
pinOut.esc.backwardLeft: 4
pinOut.esc.backwardRight: 17

#Beeper GPIO
pinOut.beeper: 21

#Reciever GPIO
pinIn.reciever.leftVercical: 10
pinIn.reciever.leftHorizontal: 9
pinIn.reciever.rightVertical: 5
pinIn.reciever.rightHorizontal: 6
pinIn.reciever.switcherLeft: 0
pinIn.reciever.switcherRight: 0

#Sticks calibration ms
calibration.leftHorizontal.max: 2001.0
calibration.leftHorizontal.min: 999.0
calibration.leftVertical.max: 2000.0
calibration.leftVertical.min: 999.0
calibration.rightHorizontal.max: 2001.0
calibration.rightHorizontal.min: 999.0
calibration.rightVertical.max: 2001.0
calibration.rightVertical.min: 999.0

#PID params
roll.P: 1.35
roll.I: 0.005
roll.D: 5.5
pitch.P: 1.45
pitch.I: 0.005
pitch.D: 5.5
yaw.P: 1.45
yaw.I: 0.005
yaw.D: 5.5
