#Accelerometr & Gyroscope GPIO
pinOut.accelerometr: 2
pinOut.gyroscope: 3

#ESC controllers GPIO
pinOut.esc.forwardLeft: 14
pinOut.esc.forwardRight: 15
pinOut.esc.backwardLeft: 17
pinOut.esc.backwardRight: 4

#Beeper GPIO
pinOut.beeper: 21

#Reciever GPIO
pinIn.reciever.leftVercical: 10
pinIn.reciever.leftHorizontal: 9
pinIn.reciever.rightVertical: 5
pinIn.reciever.rightHorizontal: 6

#Sticks calibration ms
calibration.leftHorizontal.max: 2001.0
calibration.leftHorizontal.min: 999.0
calibration.leftVertical.max: 2000.0
calibration.leftVertical.min: 999.0
calibration.rightHorizontal.max: 2001.0
calibration.rightHorizontal.min: 999.0
calibration.rightVertical.max: 2001.0
calibration.rightVertical.min: 999.0

#PID params
roll.P: 1
roll.I: 0.04
roll.D: 1
pitch.P: 1
pitch.I: 1
pitch.D: 1
yaw.P: 1
yaw.I: 1
yaw.D: 1
