#Accelerometr & Gyroscope GPIO
pinOut.accelerometr: 2
pinOut.gyroscope: 3

#ESC controllers GPIO
pinOut.esc.forwardLeft: 17
pinOut.esc.forwardRight: 4
pinOut.esc.backwardLeft: 14
pinOut.esc.backwardRight: 15

#Beeper GPIO
pinOut.beeper: 21

#Reciever GPIO
pinIn.reciever.leftVercical: 10
pinIn.reciever.leftHorizontal: 9
pinIn.reciever.rightVertical: 5
pinIn.reciever.rightHorizontal: 6